from dotenv import load_dotenv
from typing_extensions import TypedDict
from typing import (Optional, Literal)
import os
from openai import OpenAI

from langgraph.graph import (StateGraph, START, END)

load_dotenv()


# =========================
# STATE
# =========================

class State(TypedDict):

    user_query: str
    llm_output: Optional[str]
    is_good: Optional[bool]


# =========================
# OPENAI CLIENT
# =========================

client = OpenAI(
    api_key=os.getenv("GEMINI_API_KEY"),
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
)


# =========================
# NODE 1
# =========================

def chatbot(state: State):
    print("\nChatbot Node\n")
    print(state)

    response = client.beta.chat.completions.parse(
        model="gemini-3.1-flash-lite",
        messages=[
                {
                    "role": "user",
                    "content":
                        state.get("user_query")
                }
            ],
    )
    
    state["llm_output"] = (
        response
        .choices[0]
        .message
        .content
    )

    return state


# =========================
# CONDITIONAL NODE
# =========================

def evaluate_response(state: State) -> Literal["chatbot_gemini","end_node"]:

    print("\nEvaluate Node\n")
    print(state)

    # Simulated evaluation
    response = client.beta.chat.completions.parse(
        model="gemini-3.1-flash-lite",
        messages=[
                {
                    "role": "user",
                    "content":
                        f'Evaluate the following response: "{state.get("llm_output")}". Is it a good response to the query: "{state.get("user_query")}"? Return true if it is a good response, false otherwise.'
                }
            ],
    )
    
    evaluation_is_good = (
        response
        .choices[0]
        .message
        .content
    )

    if evaluation_is_good:
        return "end_node"

    return "chatbot_gemini"


# =========================
# FALLBACK NODE
# =========================

def chatbot_gemini(state: State):
    print("\nChatbot Gemini Node\n")
    print(state)

    # Simulated fallback response
    state["llm_output"] = (
        "Fallback response "
        "generated by Gemini"
    )

    return state


# =========================
# END NODE
# =========================

def end_node(state: State):
    print("\nEnd Node\n")
    print(state)

    return state


# =========================
# GRAPH BUILDER
# =========================

graph_builder = StateGraph(State)


# =========================
# REGISTER NODES
# =========================

graph_builder.add_node("chatbot", chatbot)
graph_builder.add_node("chatbot_gemini", chatbot_gemini)
graph_builder.add_node("end_node", end_node)


# =========================
# EDGES
# =========================

graph_builder.add_edge(START, "chatbot")
graph_builder.add_conditional_edges("chatbot", evaluate_response)


# =========================
# CONDITIONAL EDGE
# =========================


graph_builder.add_edge("chatbot_gemini", "end_node")
graph_builder.add_edge("end_node", END)


# =========================
# COMPILE GRAPH
# =========================

graph = graph_builder.compile()


# =========================
# INVOKE GRAPH
# =========================

updated_state = graph.invoke({"user_query": "What is 2+2?"})


print("\nUpdated State\n")

print(updated_state)